
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpsgame
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 146335578023.dkr.ecr.ca-central-1.amazonaws.com/motilayo/rpsgame:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000